# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6f34fa76c04f8c72adc72d502f1cce7fb44afc35acd40bb9a9c9c7227b7e45f089d95ae4516ff823d001eb2c99ded156d64163099600e657196d6e80f5462ea3

test:
  secret_key_base: 347769fc52aeece261fc974b6a4051254a5b578fc8236aa284a70e3d28bf51f96c814161d605fd466b27a67da241d7f94f5bab691aa3a6fb4a12d84b929b0ce3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
